pkolaczk/fclones

src/config.rs
src/main.rs
src/report.rs

This commit adds the option `-o <file>` that redirects
output to a file.
Fixes #8.

Optionally write report to a file instead of stdin

---

Cargo.toml
src/config.rs
src/files.rs
src/lib.rs
src/main.rs
src/transform.rs

A new option --transform <command> was added.
Limitations: Linux/Unix only.
Implements #6.

Transform files through external command

---

README.md

Some shells (e.g. Windows default shell) don't support path globbing,
and some examples in the docs would fail in these shells.
Fixes #17

Fix some examples and add documentation on path-globbing traps

---

Cargo.lock
Cargo.toml
src/lib.rs
src/main.rs
src/pattern.rs
src/regex.rs
src/selector.rs

Effects:
- The precision of partial matching is slightly worse
now, but it doesn't affect correctness. The most common case
with a fixed prefix is handled, so that shouldn't be a problem
in normal use.
- Negative match support had to be removed.
- Portability should be better now as we don't have to link
to system pcre libs.
- Worst case performance of regex matching is better.
Fixes #41

Replace pcre with regex crate

---

src/main.rs
src/report.rs

If the report contained CRLF sequence after the group header line,
an attempt to run `fclones remove` or `fclones link`
resulted in the following error:
Failed to read file list: Malformed group header: <path>
Fixes #58

Accept report lines ended with CRLF (Windows) Interrupt processing of report immediately on the first error

---

Cargo.lock
Cargo.toml
src/device.rs

To set proper concurrency levels, fclones needs to know the parent physical
device name storing given partition. We don't want to send parallel
requests to a single rotary drive when the files are stored in multiple
partitions of it. Unfortunately block_utils which was used to get the
parent device performed an excessive number of traversals of sysfs, which
slowed down fclones initialization.
This commit switches from querying sysfs to a heuristic based on Linux
device naming conventions. It might not be as accurate as the old function,
but an inaccuracy there can at worst cause incorrect number of threads
accessing the device. Fortunately, if that ever happens, the user can
manually override the sizes of the thread pools.

Don't scan sysfs on startup

---

README.md
src/config.rs
src/dedupe.rs
src/device.rs
src/main.rs
src/path.rs

The move command moves duplicate files to a
different directory. If files reside on the same
file system (mount point), rename command is used.
If files reside on different file systems, the file
is copied and the original is removed.
The directory structure is preserved.
The new syntax:
fclones move <target_dir>

Implement `fclones move` command

---

.circleci/config.yml
Dockerfile

Commit 09e2c7790db6 removed the dependency on `libudev-sys` which means fclones no longer needs libudev installed on the host.

Remove libudev dependency from CI and build processes

---

src/lib.rs

The non-determinism can be observed as follows:
`mkdir d; echo foo > d/1; cp d/1 d/2; ln d/1 d/3` and then `fclones group d`:
Which of the two hardlinked files is chosen is random because the ordering inside the `BTreeMap` changes (on purpose).
Sorting the file group fixes that.

Make group output deterministic with existing hardlinks

---

README.md
src/config.rs
src/lib.rs
src/main.rs

This introduces a new flag `-I` / `--isolate`. If this flag is set, all duplicates found
within the same directory argument are counted as one.
Closes #65

Option to not match files in the same dir given as argument 

---

src/lock.rs

Different Unixes seem to have flock differing by
the set of fields. We don't need those fields in this case,
so we just initialize them to zero.
Fixes #85

Make initializing libc::flock more portable

---

src/dedupe.rs

On some systems, ctime is not available.
Actually the test does not need ctime at all
to test grouping by root.
Fixes #104

Don't use ctime in isolated_roots test

---

Cargo.lock
Cargo.toml
src/arg.rs
src/dedupe.rs
src/lib.rs
src/lock.rs
src/main.rs
src/path.rs
src/reflink.rs
src/report.rs
src/transform.rs
src/walk.rs

Paths stored in reports are now in STFU-8 format,
which escapes non-UTF8, special and control characters,
so that text files produced by fclones are always valid UTF-8.
Additionally, newlines won't mess up the report file format.
A side effect of this change is that on Windows, the backslash
character ('\') used as a directory delimiter is
encoded as a double backslash '\\'.
Fixes #102

Fix handling of non-unicode and control chars in paths

---

Cargo.toml
src/reflink.rs

Version 0.1.3 of the reflink crate does not compile with the musl libc.
However this lib is only used for "crosstesting" on Linux, the tool
itself already calls the ioctl for file cloning directly.
---
Fixes #95

Only use the reflink crate on Linux for tests

---

Cargo.lock
Cargo.toml
README.md
src/config.rs
src/group.rs
src/walk.rs

Additionally, the options for controlling hidden files selection
have been changed. `--skip-hidden` has been removed, and replaced
with `--hidden` which has the opposite meaning. The short option
for including hidden files is `-.` as in ripgrep.
`-A` has been repurposed to mean `--no-ignore`
(A stands for "All files").
Fixes #101

Respect .gitignore and .fdignore. Skip hidden files by default.

---

src/config.rs
src/file.rs
src/group.rs
src/walk.rs

A new flag is added: -S | --symbolic-links.
When set, fclones treats symbolic links to files as regular files
and reports links instead of link targets.
Fixes #100

Add option to output symbolic links to files

---

src/config.rs
src/dedupe.rs
src/error.rs
src/lock.rs
src/main.rs
src/reflink.rs

Use --no-lock to disable locking.
Useful on filesystems that don't support locking at all.
Fixes #121.

Add an option to skip locking files

---

src/config.rs

Currently --cache doesn't have any effect if --transform is given.
This limitation will be removed in the future, but it requires
more work on caching.

Don't allow to use --cache with --transform

---

README.md

I assume that --caseless was renamed to -i at some point.

Updated '--caseless' to '-i' in exiv2 example

---

src/file.rs
src/group.rs

This optimization speeds up processing if the file tree contains
symbolic or hard links. Symbolic and hard links to the same data
will be hashed at most once. The algorithm is also smart enough
to not hash the data at all, if it determines that no other (unlinked)
matches are possible.
Fixes #139.

Don't hash files with same inode identifiers more than once

---

Cargo.lock
Cargo.toml
src/config.rs
src/group.rs

The filter was not applied on items matched by pre-filter
which in some cases led to incorrect reporting of unique files.
Fixes #148

Apply post_group_filter in rehash on all groups

---

src/file.rs

Before:
warn: Permission denied (os error 13)
After:
warn: Failed to read metadata of /.../file.txt: Permission
denied (os error 13)
Fixes #147

Display path in the warning msg when file metadata can't be accessed

---

Cargo.toml

Add required minimum version of Rust (1.63.0) to build master. No way to compile with 1.59, 1.60, 1.61, 1.62, 1.62.1 versions.
The error is:
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
--> src/hasher.rs:264:42
|
264 |             HashFn::Metro => file_hash::<MetroHash128>(chunk, self.buf_len, progress),
|                                          ^^^^^^^^^^^^ explicit generic argument not allowed
|
= note: see issue #83701 <https://github.com/rust-lang/rust/issues/83701> for more information
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
--> src/hasher.rs:266:41
|
266 |             HashFn::Xxh3 => file_hash::<Xxh3>(chunk, self.buf_len, progress),
| …

Check Rust version in cargo

---

src/group.rs

Should this be usize instead of u64? It has the same size as u64 on 64-bit platforms and size of 4 bytes on 32-bit platforms. 
'Cause of this fixed usage project doesn't compile for mips platform for example.
https://github.com/pkolaczk/fclones/blob/0fcad39914323bddc5268f8532f1e21cfb32b3ca/src/group.rs#L618

Fix compilation on non 64-bit targets

---

src/hasher.rs

Use `NamedTempFile` to avoid using the same, clashing filenames when several hash tests are run concurrently.
This fixes #179.
<hr>
I ran `while true; do nice /run/current-system/sw/bin/cargo test test_file_hash || break; done` on NixOS 22.11 to confirm that this actually fixed the problem.

Fix race condition in test_file_hash causing spurious test failures

---

src/file.rs

Add missing type cast.
Windows file identifiers are 128-bit.

Fix compilation on windows

---

src/dedupe.rs
src/path.rs

Paths on Windows can have a multi-component root.
E.g. C:\ is encoded as two components
'C:' and '\'. Unfortunately Path::root() and
Path::strip_root() didn't account for that properly and stripped only the first component instead of stripping the whole root. That led to incorrect path processing in `fclones move` command and panic.
Fixes #185

Fix panic caused by path prefix on Windows

---

src/file.rs
src/group.rs
src/lib.rs
src/rlimit.rs

Given enough CPU cores and the multiplication factor fclones uses, the number of threads and therefore approximately the maximum number of open files can exceed the usual limit of 1024 on Linux. On macOS this tends to be even lower.
Then some of the "fetch file extents mapping" and "compute hash of file" steps fail with "Too many open files (os error 24)".
To fix this, retrieve the current limit, increase it if possible and stay below it.
Only used on Unix systems.

Obey the open file descriptor limit when grouping files

---

src/config.rs
src/dedupe.rs
src/file.rs
src/group.rs

Falling back to softlinks between different devices is dangerous and can lead to data loss. It is better to just fail and let the user specify if they want symbolic links manually.
Now fclones will attempt to create hard links only within the same filesystem.
Fixes #196

Remove fallback to symbolic links

---

src/rlimit.rs

fixes build error for 32-bit targets.

rlimit.rs: fix return type of rlimit_nofile on 32-bit systems

---

Cargo.lock
fclones-gui/src/bytes_entry.rs

When the max size slider was set manually to Unlimited position, it did not update the model properly. So instead of unlimited, the real limit was about 850 GB.
Fixes #209

Fix max size slider not sticking to Unlimited setting

---

Cargo.lock
fclones-gui/src/input.rs

Disable "Find duplicates" button when input paths list is empty

---

Cargo.lock
fclones-gui/Cargo.toml
fclones/Cargo.toml
fclones/src/lock.rs
fclones/src/transform.rs

Vulnerabilities found in an old version of nix.
Fixes dependabot alerts.

Update nix to 0.26.2, bump up fclones to 0.32.1

---

fclones/src/config.rs
fclones/src/dedupe.rs

One use case for ctime is to find, or rather guess, which file was the original after `cp -a` was used. If a snapshot was taken of the filesystem, then keeping data of the one already in the snapshot saves space.
Also removed misleading dead code, this was not detected because the enum is public. I was wondering why `Err(format!("The priority {s} is not supported on Windows"))` would not run!

Add sorting by status change (ctime) on unix

---

fclones/src/dedupe.rs

There is no `cp --reflink` on macOS
It is `cp -c` instead
fixes: https://github.com/pkolaczk/fclones/issues/219

correct CoW command for macOS

---

fclones/Cargo.toml

Explicitly specify required features from the nix crate: "user", "fs" and "ioctl".
Closes #225

Explicitly specify required features from the nix crate

---

Cargo.lock
fclones/Cargo.toml
fclones/src/log.rs
fclones/src/progress.rs

Replaced indicatif with status-line.
The code got actually shorter and now there are even progress bar tests.
This also opens ability to display more information next to progress bar in the future.
Fixes #217

New progress bar rendering without indicatif

---

Cargo.lock
fclones/Cargo.toml
fclones/src/cache.rs
fclones/src/hasher.rs

By reporting cache flushing problems to the caller, we can log those errors through Log instead of using eprintln.
Additionally, flush errors at exit are also logged now.

Report cache flusher errors to the caller

---

fclones/src/log.rs
fclones/src/progress.rs

Fixes a bug accidentally introduced in 0.33
by the progress bar rewrite. Reporting diagnostics to stdout messed up the output.
Fixes #241

Report diagnostic output to stderr

---

packaging/Dockerfile

This allows building packages compatible with older libc.

Downgrade builder image to Debian 10 (buster), remove unneeded pkgs

---

Cargo.lock

Add dependencies that support the loongarch64 architecture [rust-lang/libc#2765](https://github.com/rust-lang/libc/pull/2765)

deps: bump libc from 0.2.149 to 0.2.155

---

fclones/src/config.rs
fclones/src/group.rs
fclones/src/hasher.rs
fclones/src/main.rs
fclones/src/reflink.rs
fclones/src/report.rs
fclones/src/semaphore.rs
fclones/src/walk.rs

Can be overridden by `--progress=[true/false/auto]`. Previous
option `--quiet` hidden, but kept for compatibility.
----
Avoids  getting mailed or logging a bunch of `[<===>            ]` lines. Also contains two clippy fix commits for v1.84.

By default, only report progress when stderr is a terminal

---

.circleci/config.yml
Cargo.lock
fclones/Cargo.toml
fclones/src/file.rs
fclones/src/group.rs
fclones/src/path.rs

- **Fix clippy lints for 1.85**
- **Upgrade clap to 4.5, anstream to 0.6.18 to fix vulnerability**

fix clippy
